### ISSUE TITLE
Error: node_modules/minify/bin/minify: No such file or directory

### ISSUE THREAD

**Issue by Edenharder** [Changaco/gitit-bootstrap#1]
Hi, when I install there is some errors

```
./build.sh: line 19: /Wiki/node_modules/minify/bin/minify: No such file or directory
```

And the math formula will not show up when I install grit-bootstrap.

**Comment by Changaco** [comment]
Upstream changed the name of the minify script and how it treats arguments a while ago. I've adapted `build.sh` to these changes.
